### ISSUE TITLE
Extension needs for Gantry 5

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#214] opened 2020-10-30 11:22 UTC
> To avoid long discussions about details on Gantry in other discussions, I'm creating this specific issue to collect info. Once we identify specific needs that should go in scssphp, we'll create dedicated issues to track them.

Gantry5 is [extending the compiler](https://github.com/gantry/gantry5/blob/feature/v5.5.0/src/classes/Gantry/Component/Stylesheet/Scss/Compiler.php).

Here is what I can see being done:

- registering custom functions through `registerFunction` in `__construct` => a composition-based approach might work as a replacement as inheritance is not necessary to achieve the registration
- registering a `url` function through the `Compiler::lib*` discovery => can be migrated to `registerFunction` as this does not override a core function
- configuration methods for the implementation of custom functions => not relevant for scssphp. They would be moved to wherever the custom functions go when using composition
- override `get` to catch any exception, and treat them as echoing the exception message (no idea where it would end up) and return an empty string as the value
- overriding `Compiler::parserFactory`
- overriding `Compiler::addParsedFile` and `getParsedFiles` with almost the same logic than upstream
- overriding `Compiler::importFile`
- adding `Compiler::$streamNames`
- overriding `Compiler::handleImportLoop` to use `$streamNames` instead of `$sourceNames`

@mahagr can you give us some explanations about the use cases for overriding `get`, overriding `parseFactory`, reimplementing the `parsedFiles` feature and replacing `Compiler::importFile` ?

Regarding `Compiler::importFile`, I'm wondering in particular if your use case could be solved in other ways:
- adding a callable in the importPaths, which allows custom resolution
- overriding `Compiler::findImport` rather than `Compiler::importFile` (and if this has to be done over using a callable in `importPaths`, why is it necessary ?)

Edit: see https://github.com/gantry/gantry5/blob/feature/v5.5.0/src/classes/Gantry/Component/Stylesheet/ScssCompiler.php for the new version of the code

**Comment by mahagr** [comment] 2020-10-31 07:59
Let me do some minor rewriting based on what we've talked this far. I'll get back to you ASAP with cleaned up code. I will move everything that can be moved outside of the class override.

Many of the core overrides are there because of `$this->parsedFiles` used to be private. As it doesn't seem to be that anymore, I can clean up those and see what remains.

As I said before my main grief with the import file logic is not our use of streams (urls), but the following line:

https://github.com/scssphp/scssphp/blob/master/src/Compiler.php#L4855

It basically prevents user overrides from working with the compiler without manually deleting the cache file whenever user adds a new file. Is this is something that should be fixed in the library itself?

**Comment by Cerdic** [comment] 2020-10-31 09:57
Maybe I can answer on this as I think I’m the one that wrote this line.

It’s all about cache efficiency and performance vs cache invalidation (you know one of the 2 big issues in computer science with naming things)

When I wrote the cache part I try to find a good balance between performance and invalidation and indeed I decided that checking the timestamp of previously parsed files was fast enough to be an automatic cache invalidation condition whereas searching for a possible new file overriding the one already in parser cache, which means traversing the full path times the number of imported files, is not so acceptable.

When you are using the lib in the production, in your http hit, the normal situation which will occurs 99% of time is that nothing changed and you want the compilation to be as fast as possible in this case.

Sometimes one imported file was modified, then it as to be reparsed and the full Scss has to be compiled.

The case when the file source itself changes is quite rare and happening mainly in developpement mode. So I decided that when this is happening it’s ok to require a forced parsing and compilation of everything. This is why you have an option to force the refreshing of the cache.

In the CMS I’m working with this is managed through an administration button available for the logged user that allow to force a cache refreshing (in fact this is a global button, not only for scssphp cache, but the scssphp plugin is also triggered by the button)

So we can of course discuss this choice but it feels to me that trying to manage this in the scssphp would have a performance impact on the production scenario for solving a quite rare case, and I decided that the user of the Library should manage this point on this side.

You could also have a development mode where the scssphp cache is deactivated.

However feel free to dig in that and propose a patch to improve this strategy or propose an alternate cache management option that would not only check the timestamps but also check of a new file is available in the path...
Le 31 oct. 2020 à 09:00 +0100, Matias Griese <notifications@github.com>, a écrit :
	As I said before my main grief with the import file logic is not our use of streams (urls), but the following line:
https://github.com/scssphp/scssphp/blob/master/src/Compiler.php#L4855
It basically prevents user overrides from working with the compiler without manually deleting the cache file whenever user adds a new file. Is this is something that should be fixed in the library itself?

**Comment by mahagr** [comment] 2020-10-31 12:28
Right now I have production mode with no checks at all (there's cache clear if something gets installed) and development mode, which uses caching, but invalidates on any changes (where all the changes are users adding their own override files). With the cache disabled the performance just isn't there as the amount of SCSS code is high.

So we are really using this feature for development and still getting acceptable performance. In our case the cost is not that high as there is some logic in the stream wrapper to make sure only some paths are looked into (we know that the rest won't change). 

So it's a bit more advanced use case than usually which is why the code was overridden in the first place. Developers were just not happy with the original behavior -- but this was maybe 4 years ago. SCSS parsing hasn't really changed since it was finallized except for keeping it up to date. The library has changed a lot since then, though, which I really appreciate!

So.. In short (what I can remember without digging deeper) is that we use either relative paths or uris in cache because of in our case caching was just meant to speed up reloads on development mode. In production there are some checks now and then, but it mostly relies that updates clear cache and that there aren't any other updates.

**Comment by stof** [comment] 2020-11-01 00:49
@mahagr regarding your registration of a sass `url` function, I think it would be great to investigate a different approach.

Looking at the official sass implementations, they forbid defining a function named `url` (among a small list of special names) because the CSS syntax requires a special parsing rule (dart-sass forbids that altogether while libsass triggers a warning).
To be able to be spec compliant, we will probably need to introduce a similar restriction in 2.0.

Maybe providing a `gantry-theme-url()` instead of overloading the CSS `url` function could be an option ?

**Comment by mahagr** [comment] 2020-11-02 10:01
I've updated the file to remove all the custom functions from it (there is a separate class for that now). I also updated the existing methods to better match the latest version of the compiler class...

We cannot really change the behavior with `url()` anymore as there are hundreds of themes already using the method, not to mention a huge number of sites which rely on this behavior. The method is overridden to make it possible to have the files in different locations in different CMSes -- without this functionality it is impossible to map the file locations correctly in every environment. Either we override the method or we need to do it outside of the parser, which is extra pass over the files and error prone. For me, it would be enough to have a hook in the class to allow me to see the content of the url node and replace it if needed.

BTW, I have some extra logic in the class, such as `cleanParsedFiles()` together with a minor change in `importFile()` to allow the same SCSS compiler instance to run multiple times on different files. This speeds up the compile times a lot, if you need to compile multiple files using the same imports. For example we use it to compile all theme variants at the same time.

**Comment by stof** [comment] 2020-11-02 10:40
> BTW, I have some extra logic in the class, such as `cleanParsedFiles()` together with a minor change in `importFile()` to allow the same SCSS compiler instance to run multiple times on different files. This speeds up the compile times a lot, if you need to compile multiple files using the same imports. For example we use it to compile all theme variants at the same time.

scssphp has a `Cache` that can cache the parsing step (and also the compilation step btw) for that case.

**Comment by stof** [comment] 2020-11-02 13:00
@mahagr see also #237 about that cache.

**Comment by stof** [comment] 2020-11-02 13:36
btw, your "minor change" where you populate `parsedFiles` even when using the `importCache` looks like a bug to me. `$this->importCache` is currently leaking between multiple calls to `compile()` (and keeps its growing content forever) while the code using it assumes it is per compilation (like other state of the compiler). The `Cache` should be used to cache things accross compilations

**Comment by stof** [comment] 2020-11-03 02:19
@mahagr what is the reason to override `->get()` to catch exceptions ?

**Comment by stof** [comment] 2020-11-04 09:11
@mahagr the issue with registering `url()` as a function to rewrite the URL cannot be doen for a spec-compliant Sass parser. An unquoted URL is not a valid SassScript expression: https://sass-lang.com/documentation/syntax/special-functions#url
As the whole point of 2.x is becoming spec compliant (2.0 probably won't achieve it yet, probably more a further minor version, if we manage our goal of an incremental rewrite), we will probably need to do the same and parse them as unquoted strings in the future rather than functions.

**Comment by Cerdic** [comment] 2020-11-04 09:21
There is already specials parsing for `url()` 

https://github.com/scssphp/scssphp/blob/master/src/Parser.php#L2430
https://github.com/scssphp/scssphp/blob/master/src/Parser.php#L2452
https://github.com/scssphp/scssphp/blob/master/src/Parser.php#L3823 

which means a registered `url()` function is not guaranted to be called on all `url()` occurences in the scss. It depends which kind of content it has.

**Comment by mahagr** [comment] 2020-11-09 11:10
Regarding to the minor change to populate `parsedFiles`, compiling broke without it. I will need to try to convert to use the cache and to create multiple instances of the compiler instead and see how it goes. Right now the same instance is being used multiple times. So yes, I do agree with #237 and #222, it would make things much easier.

What comes to overriding `->get()`, it was implemented back in 2015 not to fail compilation if there were undefined variables. I'm not sure we should do that anymore, so I added FIXME to it.

On `url()`, I don't really need to override the method, but I do need a way to convert the content inside it in case if internal PHP streams are being used. It's kind of the same situation as with imports; we need to convert those URIs into relative paths.

**Comment by mahagr** [comment] 2020-11-09 11:12
Another cool use for the `url()` could be to convert smaller icon files into inline CSS.

**Comment by mahagr** [comment] 2020-11-10 09:51
@stof @Cerdic 

Hey, it looks like that the latest version of the `Compiler` class cannot be overridden by Gantry anymore as it uses 2 private properties here:

https://github.com/scssphp/scssphp/blob/master/src/Compiler.php#L5281-L5284

The code is also not stream safe as `dirname()` does not work with streams like `theme://my.css`. We really need to find a solution, which allows streams to be used and a mode which checks existance of new file overrides in development mode.

**Comment by Cerdic** [comment] 2020-11-10 10:03
I was fearing a bit this kind of chain reaction when wondering if we should release a 1.3.1 on a maintenance branch or keep releasing on the master branch. Now it's done, let's deal with it.

You should really use a callable as importDir to resolve your streams in `@import` directives. It's going to be called in the `findImport()` function
https://github.com/scssphp/scssphp/blob/master/src/Compiler.php#L5309
 and you can return the file path that will be then used by the standard `importFile()` function

**Comment by mahagr** [comment] 2020-11-10 10:07
@Cerdic Nah, it's OK. I just need to find a new way to use the library and hope that my concerns on caching will be heard.

**Comment by mahagr** [comment] 2020-11-10 10:16
@Cerdic I checked the code and I am already doing that:

https://github.com/gantry/gantry5/blob/19dde2b0101c3ab6f7558213fe567347ee454088/src/classes/Gantry/Component/Stylesheet/ScssCompiler.php#L128

Rest of the logic is just to make sure that caching detects the changes in override files.

**Comment by stof** [comment] 2020-11-10 10:21
@mahagr this probably does not work, given that `findImport` is an existing method of the Compiler that you override (and precisely the one calling the importPaths callables in its built-in implementation).

**Comment by mahagr** [comment] 2020-11-10 10:28
@stof That code is years old. To be honest, after reading the code again and again, all the remaining overrides in my exctended `Compiler` class are related to cache invalidation to detect new files being added.

**Comment by mahagr** [comment] 2020-11-10 10:33
Right now I'm trying to get rid of my extended class altogether and just use the compiler as it was intended. Because the class isn't fully stateless, I need to make some changes to my code.

**Comment by stof** [comment] 2020-11-10 10:53
@mahagr do you have any kind of test setup that I could use easily to work on #256 ?

**Comment by mahagr** [comment] 2020-11-10 11:11
I responded to the issue. I don't think it's a concern anymore after I updated our code.

**Comment by mahagr** [comment] 2020-11-10 12:00
I just updated my code to fully remove extended `Compiler` class. I also changed the code to instantiate a new Compiler for every generated CSS file. I am not 100% sure if that is needed, but as I'm not anymore extending the class, I cannot do the cleanup I had implemented in it. So better to be safe than sorry. Right now I'm not using the cache.

Gantry creates its own meta file to detect if the recompilation is required -- I can likely hack it to look for the overrides as I have callable to figure out imports.

**Comment by mahagr** [comment] 2020-11-10 12:35
After looking into the code a few times during the past weeks, I think I finally understand the new code and I was, in most parts, able to update our code to take full advantage of it.

For change detection, I think I'm going to have custom logic to handle that part and register the looked up files myself from the callable. As SCSS compiler will internally use absolute paths for caching files, it should work just fine for detecting changes during the compilation. But I cannot use `getParsedFiles()` myself -- I will need to use my own for the change detection to determine if recompile is needed.

I will get back to you when I have finished the code and tested it.

If everything goes fine, the only remaining question is how to deal with the streams in `url()` function.

**Comment by stof** [comment] 2020-11-10 12:58
@mahagr can you tell me which bugs you work around related to source maps in https://github.com/gantry/gantry5/blob/55fe2485f65f54fdfd9016a7b004051ddc1b7434/src/classes/Gantry/Component/Stylesheet/ScssCompiler.php#L72-L73 ?
AFAICT, this is a perfectly valid usage of the public API (while passing a custom SourceMapGenerator is not meant to be supported according to the phpdoc, even though it can technically work for now)

**Comment by mahagr** [comment] 2020-11-10 13:09
Oh, I didn't update that really old FIXME as I didn't yet try to use the variables to save the file. Years ago when the source map support was added, there was a bug on saving the source map. I worked it around by using inline source map and extracting it here:

https://github.com/gantry/gantry5/blob/55fe2485f65f54fdfd9016a7b004051ddc1b7434/src/classes/Gantry/Component/Stylesheet/ScssCompiler.php#L152-L170

Let me fix that FIXME. :)

**Comment by mahagr** [comment] 2020-11-10 13:18
@stof Quick question: if I stop using `$compiler->getParsedFiles()` (which keeps its state over multiple compilations, see https://github.com/scssphp/scssphp/issues/237#issuecomment-720627092), do you think that can I safely compile multiple files without getting into issues?

**Comment by stof** [comment] 2020-11-10 13:23
@mahagr `$compiler->getParsedFiles()` does not keep its state (`Compiler#importCache` does and I consider it is a bug).
the issue with `$compiler->getParsedFiles()` is that it is broken when using the Scssphp Cache system (which you don't use for now).

Regarding `Compiler#importCache` not resetting itself, I'm not sure whether it can create issues in your case. but the bug is easy to fix in scssphp.

**Comment by mahagr** [comment] 2020-11-10 13:42
I think that both of them will cause issues. If you search for `parsedFiles`, it's used by the cache to set dependencies. But unfortunately, it will not be cleared between calls to `compile()`. So if you call the same instance of Compiler multiple times, it will think that the next file imports all the files from the previous call. For my use it would be handly to allow multiple files to be compiled with the same variables and registered functions.

I added support for Scssphp cache already to test it out, but yes, it seems to have some issues when I try to use it. For my purposes it would be handy to be able to cache only the parsed files.

**Comment by stof** [comment] 2020-11-10 14:05
hmm, indeed. `parseFiles` has the same issue than `importCache`

**Comment by mahagr** [comment] 2020-11-10 14:15
I've been looking at `importCache` and I don't think it has the same issue. My reasoning is that it is the same file, so the parsed tree will be identical. There are likely issues with the `Compiler#sourceNames`, though...

**Comment by stof** [comment] 2020-11-10 17:10
@mahagr answering here about your comment in https://github.com/scssphp/scssphp/issues/266#issuecomment-724764158 so that the other issue does not go off-topic by talking about a gantry extension need rather than the internal implementation of functions.

> This leaves how to deal with the current way to import functions as well as the array-based api. And hopefully a way to hook into `url()` content.

I would say that for now, things will keep working the same there. *Some* usages of URLs will be parsed as functions and so can be intercepted by a custom `url()` sass functions. But depending on the syntax used in your sass files, this might not always happen (see https://github.com/scssphp/scssphp/issues/214#issuecomment-721614360).
When we rewrite the parser in the future to be more spec compliant, that could become an issue for you, as I think dart-sass treats that more often as an unquoted string than as a function call.

Given that implementing a `url` function is forbidden in official sass, I suggest you register an additional `relative-url()` function exposing that feature, and you encourage users to use that one instead of `url()` when they need the rewriting. And maybe you show a warning when using `url()` with something relying on the rewrite...

**Comment by stof** [comment] 2021-01-27 10:32
I'm closing this issue as Gantry 5 has been refactored and does not need to extend the Compiler anymore (using the public extension points instead).
For the remaining case of registering a `url()` function to override the behavior, I won't intentionally break it for now. But the current state is already that it works _sometimes_ as CSS url references don't always comply with the syntax of scss function calls. It is possible that in the future, the cases where it indeed work would change, and I don't want to consider that covered by a BC policy (as that could forbid us to become spec-compliant). So I still strongly suggest that the Gantry team starts making plan for migrating to a new solution for that use case instead.

**Closed** 2021-01-27 10:34 UTC
