### ISSUE TITLE
PHP Version Early Deprecation?

### ISSUE THREAD

**Issue by dleffler** [scssphp/scssphp#752] opened 2024-09-13 13:31 UTC
PHP v8.1 isn't deprecated until AFTER Jan 2026, is there a reason the min PHP version was raised to PHP 8.2 a year and a half early?

**Comment by stof** [comment] 2024-09-13 13:37
The explanation is given in https://github.com/scssphp/scssphp/issues/746

The rule is this one: if someone can make the CI job work on PHP 8.1 for the new compiler (not yet merged, but will soon be), I will happily re-add support for PHP 8.1 (the code is still compatible, and I don't intent to use features requiring PHP 8.2 for now to make this work possible).
However, I will not declare the new version of scssphp compatible with PHP 8.1 if I don't have a CI job to ensure it is indeed the case. And I won't spend my own free time trying to debug why PHP 8.1 segfaults when running the testsuite on GitHub Actions (while it works on my machine).

**Comment by stof** [comment] 2024-09-13 13:38
Note that this version bump only affects the upcoming version 2.0 of the library.

The 1.x branch still supports PHP 5.6 to 8.3 and this won't change (the code triggers deprecations on PHP 8.4, which cannot be fixed while retaining support for PHP < 7.2, but it works)

**Closed** 2024-09-17 12:27 UTC

**Comment by TimWolla** [comment] 2024-10-19 13:36
> And I won't spend my own free time trying to debug why PHP 8.1 segfaults when running the testsuite on GitHub Actions (while it works on my machine).

For me running the test suite in a `php:8.1` docker container also segfaulted. Running it in a debug build of PHP 8.1 triggered an assertion failure, a debug build of PHP 8.2 succeeded. I've bisected the change to php/php-src@b3e26c3036a54e9821ea7119c26cdabe484fe36d:

```
b3e26c3036a54e9821ea7119c26cdabe484fe36d is the first new commit
commit b3e26c3036a54e9821ea7119c26cdabe484fe36d
Author: Ilija Tovilo <ilija.tovilo@me.com>
Date:   Fri Apr 19 15:19:02 2024 +0200

    Fix missing handling of CALLABLE_CONVERT in cleanup_unfinished_calls()
    
    Fixes GH-14003

 NEWS                    |  2 ++
 Zend/tests/gh14003.phpt | 24 ++++++++++++++++++++++++
 Zend/zend_execute.c     |  4 ++++
 3 files changed, 30 insertions(+)
 create mode 100644 Zend/tests/gh14003.phpt
```

```
git bisect start
# status: waiting for both good and bad commits
# old: [2c40762b4e69a6fb4d3e031326667436495cdce3] Fix error message for newer libxml
git bisect old 2c40762b4e69a6fb4d3e031326667436495cdce3
# status: waiting for bad commit, 1 good commit known
# new: [41af9335b7fa90f63b48e2c962e5d183016f5963] Fix GH-16473: dom_import_simplexml stub is wrong
git bisect new 41af9335b7fa90f63b48e2c962e5d183016f5963
# old: [4ad7e7251d323ad8caf70f9dbbf674bccf768b1e] Declare ext/sysvmsg constants in stubs (#9125)
git bisect old 4ad7e7251d323ad8caf70f9dbbf674bccf768b1e
# old: [bda28eb6498f6904dd3442d3341ba0a7eca5f4ec] Merge branch 'PHP-8.1' into PHP-8.2
git bisect old bda28eb6498f6904dd3442d3341ba0a7eca5f4ec
# old: [552ea62e1f88ad09b8838992f332b3eccbef3ba4] Fix GH-13517: Multiple test failures when building with --with-expat
git bisect old 552ea62e1f88ad09b8838992f332b3eccbef3ba4
# new: [6490a1827100c0b5da01bf9de915921ea586a281] Stop relying on the sax2 flag directly
git bisect new 6490a1827100c0b5da01bf9de915921ea586a281
# new: [3237b8f471f5f3701622c6b08a953311e24fed1f] CI: fix oci setup (#14123)
git bisect new 3237b8f471f5f3701622c6b08a953311e24fed1f
# old: [9b1d2e93b81d404815361398cea7a62bf84041e9] Fix FPM tester default env vars change
git bisect old 9b1d2e93b81d404815361398cea7a62bf84041e9
# old: [3b93f1319907a361fca5b039ad0832c67ba85425] Revert "ext/mysqlnd: support ER_CLIENT_INTERACTION_TIMEOUT"
git bisect old 3b93f1319907a361fca5b039ad0832c67ba85425
# new: [b3e26c3036a54e9821ea7119c26cdabe484fe36d] Fix missing handling of CALLABLE_CONVERT in cleanup_unfinished_calls()
git bisect new b3e26c3036a54e9821ea7119c26cdabe484fe36d
# old: [32efc76c327fc8e968a34b327f7ce5b2e205070e] Use return value of getpwuid_r(), not errno (#13969)
git bisect old 32efc76c327fc8e968a34b327f7ce5b2e205070e
# old: [1acd7a09190daad70624684b9024287479cbc073] Add missing COMPILE_IGNORE_OTHER_FILES check for static calls
git bisect old 1acd7a09190daad70624684b9024287479cbc073
# old: [cc46a4e6b5a413bab3e264c1dcaaf7052f54fbc4] ext/intl: level up c++ runtime std for icu 74 and onwards.
git bisect old cc46a4e6b5a413bab3e264c1dcaaf7052f54fbc4
# old: [04b864e56655d030894a38c9044172cf8ea361d4] Fix GH-13806: openssl_x509_parse_basic test fails with OpenSSL 3.2+ (#13961)
git bisect old 04b864e56655d030894a38c9044172cf8ea361d4
# first new commit: [b3e26c3036a54e9821ea7119c26cdabe484fe36d] Fix missing handling of CALLABLE_CONVERT in cleanup_unfinished_calls()
```

Thus the crash is related to the use of first-class callables.

**Comment by TimWolla** [comment] 2024-10-19 13:48
Making the following change is sufficient for the test suite to pass for me:

```
diff --git i/src/Value/SassNumber.php w/src/Value/SassNumber.php
index d3884323..64dde1f8 100644
--- i/src/Value/SassNumber.php
+++ w/src/Value/SassNumber.php
@@ -607,7 +607,7 @@ abstract class SassNumber extends Value
     public function greaterThan(Value $other): SassBoolean
     {
         if ($other instanceof SassNumber) {
-            return SassBoolean::create($this->coerceUnits($other, NumberUtil::fuzzyGreaterThan(...)));
+            return SassBoolean::create($this->coerceUnits($other, [NumberUtil::class, 'fuzzyGreaterThan']));
         }
 
         throw new SassScriptException("Undefined operation \"$this > $other\".");
```

Of course that does not guarantee there is no other way to trigger this bug. It's just not triggered by the test suite.

**Comment by TimWolla** [comment] 2024-10-19 14:17
The issue is also triggered by the `vendor/sass/sass-spec/spec/values/calculation/calc/error/known_incompatible/complex.hrx` tests (amongst others). It requires making this change to be reliably triggered:

```
--- i/tests/SassSpecTest.php
+++ w/tests/SassSpecTest.php
@@ -171,6 +171,16 @@ class SassSpecTest extends TestCase
         return rtrim($css);
     }
 
+    protected function setUp(): void
+    {
+        \gc_collect_cycles();
+    }
+
+    protected function tearDown(): void
+    {
+        \gc_collect_cycles();
+    }
+
     /**
      * @dataProvider provideTests
      */
```
