### ISSUE TITLE
Incompatible units error in calc() or variable

### ISSUE THREAD

**Issue by thomashigginbotham** [scssphp/scssphp#352] opened 2021-04-30 17:21 UTC
An "incompatible units" error is thrown when creating a string variable that includes an interpolated value whose unit is not the same as others in the string (e.g. `$result: 50% - #{$some-rem-unit}`). This also happens inside of `calc()` statements (e.g. `calc(50% - #{$some-rem-unit})`). Both of these cases work fine in Dart Sass.

For now, I'm having to quote then unquote the string as a workaround:

```scss
$some-rem-unit: 2rem;
$result: "50% - #{$some-rem-unit}";
width: calc(#{unquote($result));
```

**Comment by stof** [comment] 2021-04-30 17:54
Interpolation is one of the cases where our parser and compiler is not spec compliant (there is https://github.com/scssphp/scssphp/issues/157 about it).
I'm quite sure that this is the root cause here. In dart-sass, `$result` will be an unquoted string produced by the interpolation. In scssphp, we currently resolve the interpolation inside the expression (as we parse interpolation in the wrong way) and then we try to compule `$result: 50% - 2rem`.

Unfortunately, there is no easy fix for that. It requires a major refactoring of the handling of interpolation, which then implies refactoring lots of other parts (which cannot be done in a backward compatible way due to internals being opened everywhere). So this won't happen in 1.x.
Our current plan is to wrap up the 1.5 release (hopefully this weekend if I can get at it), then quickly release 2.0 making everything private, internal and final as appropriate to restrict consumers of the library to use the supported extension point, and then do some major refactorings in 2.x releases (which will ultimately become a full rewrite of the internals of the library at some point).

**Comment by stof** [comment] 2021-04-30 18:07
Actually, I was wrong saying that this cannot be fixed in 1.x. It is actually already fixed there. The upcoming 1.5 release contains some fixes about the way interpolation works, and they are enough to make this case work.

**Closed** 2021-04-30 18:07 UTC
Labels: bug, spec compliance
