### ISSUE TITLE
Cannot resolve Windows-style directory symlinks or Windows junctions for partial path

### ISSUE THREAD

**Issue by scarcloud** [scssphp/scssphp#176] opened 2020-10-13 10:00 UTC
Found in the sourcecode included in [`svewap/ws_scss`](https://github.com/svewap/ws_scss/tree/master/Resources/Private/scssphp) which resolves to v1.1.1, but after checking the current release sourcecode we think the problem has persisted.

We are using `ws_scss` to compile SCSS that consists of a base located in our site package and partials from other extensions. Running on a Windows machine, the underlying `scssphp` was not able to properly resolve a path containing a Windows-style directory symlink nor a junction.

```
`../../../../../public/typo3conf/ext/other_sitepackage/Resources/Public/Stylesheets/variables` file not found for @import: C:/path/to/repository/public/typo3conf/ext/our_sitepackage/Resources/Public/Stylesheets/style.scss on line 1, at column 0

Call Stack:
#0 import C:/path/to/repository/public/typo3conf/ext/our_sitepackage/Resources/Public/Stylesheets/style.scss (unknown file) on line 1
```

We traced back the problem to `Compiler::findImport`, where a full path is a string concatenation of the directory, a separator, and the full filename:
```
$full = $dir . $separator . $full;
```

Testing problem resolutions we could fix it by generating a `realpath` result for the concatenated string
```
$full = realpath($dir . $separator . $full);
```

Will post a pull request in a few.

I'm also linking the [related issue at `svewap/ws_scss`](https://github.com/svewap/ws_scss/issues/37).

**Comment by robocoder** [comment] 2020-10-13 17:30
This isn't a Windows issue. The import path should be an absolute path.

**Comment by robocoder** [comment] 2020-10-15 21:55
The root cause is within this snippet of code from `Compiler.php` where it tries to see if `$full` is an absolute path:
```
                    $separator = (
                        ! empty($dir) &&
                        substr($dir, -1) !== '/' &&
                        substr($full, 0, 1) !== '/'
                    ) ? '/' : '';
```

**Comment by YetiCGN** [comment] 2020-10-16 14:30
> This isn't a Windows issue. The import path should be an absolute path.

But it cannot be because absolute paths vary from system to system. It needs to be relative to the current TYPO3 extension path and refer to another TYPO3 extension. It would help though if we could specify a path relative to project root dir.

**Comment by Cerdic** [comment] 2020-10-21 09:18
I proposed an alternative patch in the PR, but I'm not sure if this is fixing your issue and an acceptable change for us.

That said, my opinion is the answer of ws_scss maintainer in https://github.com/svewap/ws_scss/issues/37 is a bit easy and not really digging in the possibilities allowed by ScssPHP.

I'm maintaining myself a CMS plugin embeding ScssPHP and I have no issue with relative directories, multiples extensions and paths, as ScssPHP is providing all what you need to adapt the import resolving to your environment:
- you can provide import paths, allowing the then to specify import relatively to any of these import paths - here the ws_scss extension could declare the project root dir as an import path
- you can even provide a full own made function to handle imports, in which you could take in account this kind of situation

So I would tend to say this is an implementation issue in the ws_scss extension, not a core issue in ScssPHP

**Comment by stof** [comment] 2020-10-21 10:20
@Cerdic we still have an issue in the detection of absolute path to be compatible with Windows, according to the code snippet given by @robocoder

**Comment by stof** [comment] 2021-01-22 09:23
@scarcloud can you try again with 1.4.1 ? I think https://github.com/scssphp/scssphp/pull/288 solved this as it now detects absolute paths for Windows too.

**Comment by stof** [comment] 2022-02-26 00:03
Closing this as no answer was provided since 1 year

**Closed by stof** 2022-02-26 00:03 UTC
Labels: Waiting answer
