### ISSUE TITLE
1.5.2 fails with Only 1 argument allowed, but 2 were passed.

### ISSUE THREAD

**Issue by magicdude4eva** [scssphp/scssphp#420] opened 2021-05-26 20:33 UTC
Error: Only 1 argument allowed, but 2 were passed on line 6, at column 5
```scss
@mixin form-control-focus($color: $input-border-focus) {
  $color-rgba: rgba(red($color), green($color), blue($color), .6);
  &:focus {
    border-color: $color;
    outline: 0;
    @include box-shadow(inset 0 1px 1px rgba(0,0,0,.075), 0 0 8px $color-rgba);
  }
}
```

**Comment by magicdude4eva** [comment] 2021-05-26 21:03
Sorry for initial incorrect submission. This is broken with 1.5.2. Reverting back to 1.4.1 does not throw the error and everything seemingly works.

**Comment by stof** [comment] 2021-05-27 07:47
Can you give  a full reproducing case ?

**Comment by stof** [comment] 2021-05-28 12:10
@magicdude4eva any chance to provide a full reproducing case (i.e. a scss file that we can compile to get the error) ? Your code snippet is incomplete (it never use the mixin, so the code won't do nothing, and trying to run it would break due to using other mixins not part of the code snippet)

**Comment by magicdude4eva** [comment] 2021-05-28 17:52
Sorry for the delay - I will get you the info by Monday.

**Comment by stof** [comment] 2021-05-31 13:55
@magicdude4eva please don't forget about this one. I'm interested into knowing whether our 1.5.2 release is really broken

**Comment by stof** [comment] 2021-06-11 12:32
Closing due to lack of answer providing the requested info

**Closed by stof** 2021-06-11 12:32 UTC
