### ISSUE TITLE
Error with Bootstrap 5 - Fatal error</b>:  Uncaught ScssPhp\ScssPhp\Exception\SassScriptException: $color1: null is not a color. in

### ISSUE THREAD

**Issue by klebinhopk** [scssphp/scssphp#440] opened 2021-06-30 18:43 UTC
Good afternoon devs.
Guys is the following I'm having a problem using the scssphp lib with Bootstrap v5.0.2.
I tried to debug the bootstrap core a little and came across two imports that are causing this error...

Inside the /scss/bootstrap.scss file
The first is the:
  @import "_tables.scss";
The second is the:
  @import "_button.scss";

On line 132 of _tables.scss
It has the following excerpt "@each"

@each $color, $value in $table-variants {
   @include table-variant($color, $value);
}

When I remove this excerpt the error disappears, I would like to know if anyone has a solution for this case.

![image](https://user-images.githubusercontent.com/16194393/124014312-bd1e7880-d9b9-11eb-882f-9599cccd5418.png)

**Comment by stof** [comment] 2021-07-01 08:00
Duplicate of #434 that is already fixed in the 1.x branch. I will do the release in the following days.

**Closed by stof** 2021-07-01 08:00 UTC

**Comment by stof** [comment] 2021-07-02 16:37
The release is now done.
