### ISSUE TITLE
Suggested alternatives do not work for 'Passing raw values to as custom variables to the Compiler is deprecated'

### ISSUE THREAD

**Issue by JornJorn** [scssphp/scssphp#568] opened 2022-04-18 16:01 UTC
Hello,
I saw the following deprecating warning:
Passing raw values to as custom variables to the Compiler is deprecated. Use "\ScssPhp\ScssPhp\ValueConverter::parseValue" or "\ScssPhp\ScssPhp\ValueConverter::fromPhp" to convert them instead.

Currently, I give this as input to AddVariables:
![afbeelding](https://user-images.githubusercontent.com/81434299/163836022-5811edaa-3562-4bb7-af6c-aa6497b73789.png)

When I use parseValue on the value, I get:
![afbeelding](https://user-images.githubusercontent.com/81434299/163836239-0c200649-f372-476c-b5a5-b17c1a654659.png)

And when I use fromPhp on the value, I get:
![afbeelding](https://user-images.githubusercontent.com/81434299/163836315-0be0ee46-b62b-40c1-8ad4-4efde91df375.png)

Am I doing something wrong or is the suggested fix for this deprecation warning incorrect?

**Comment by stof** [comment] 2022-04-19 07:16
Why do you think this is incorrect ?

**Comment by stof** [comment] 2022-04-19 12:18
Note however that getting different values when using `fromPhp` or `parseValue` is totally expected. Those 2 methods are not doing the same (which is precisely why we have 2 of them).

**Comment by JornJorn** [comment] 2022-04-19 12:26
I understand both of them should give different results. However, no one gives me the desired result (the first image).  What function should I use for that?

**Comment by stof** [comment] 2022-04-20 15:51
Please provide a reproducing case for the actual issue you have

**Comment by JornJorn** [comment] 2022-04-20 15:55
My issue; using the suggested alternative, assets do not convert as they should

**Comment by stof** [comment] 2022-04-20 16:00
And this is not something I can reproduce using only that sentence, as there is nothing about asset conversion in `addVariables`. So your issue probably involves other parts (maybe even something not happening in scssphp itself).

That's why I'm asking for a reproduction of the issue. Otherwise, there is nothing more I can do to help you.

**Comment by stof** [comment] 2022-05-12 17:39
Closing due to lack of answer

**Closed by stof** 2022-05-12 17:39 UTC
Labels: Waiting answer
